# Generated by Django 4.2.21 on 2025-07-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('votes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('candidate_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_app.position')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_app.department')),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
