# Generated by Django 4.2.21 on 2025-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_app', '0002_alter_position_options_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
    ]
